# Generated by Django 6.0 on 2025-12-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
