# Generated by Django 6.0 on 2025-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_apikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='hashed_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
