# Generated by Django 6.0 on 2025-12-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_apikey_hashed_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='hashed_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
