# Generated by Django 6.0 on 2025-12-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_apikey_hashed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='create_dummy_key',
            field=models.BooleanField(default=False, help_text='Create a dummy key for testing purposes. Key is `dummy-key`.'),
        ),
    ]
