# Generated by Django 6.0 on 2026-01-25 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_populate_project_apikey_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="uid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="uid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
