# Generated by Django 6.0 on 2025-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawSpan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trace_id", models.CharField(max_length=32)),
                ("span_id", models.CharField(max_length=16)),
                (
                    "parent_span_id",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=32)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("attributes", models.JSONField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trace_id"], name="ingest_raws_trace_i_c50025_idx"
                    ),
                    models.Index(
                        fields=["ingested_at"], name="ingest_raws_ingeste_65eb53_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trace_id", "span_id"), name="unique_raw_span"
                    )
                ],
            },
        ),
    ]
