# Generated by Django 6.0 on 2025-12-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawspan",
            name="projected",
            field=models.BooleanField(default=False),
        ),
    ]
