# Generated by Django 6.0 on 2025-12-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_rawtrace_and_more'),
        ('projects', '0004_alter_apikey_hashed_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawTrace',
            new_name='RawTraceOLD',
        ),
    ]
