# Generated by Django 6.0 on 2026-01-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0003_rename_payload_rawtrace_payload_json_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawtrace",
            name="payload_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
