# Generated by Django 6.0 on 2026-01-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0004_alter_rawtrace_payload_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawtrace",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
