# Generated by Django 6.0 on 2026-01-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0010_trace_service_name_alter_span_system_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="uid",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="trace",
            name="uid",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
    ]
