# Generated by Django 6.0 on 2026-01-25 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0012_populate_trace_span_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="span",
            name="uid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="trace",
            name="uid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
