# Generated by Django 6.0 on 2026-01-25 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0014_rename_trace_id_to_otel_trace_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="span",
            old_name="span_id",
            new_name="otel_span_id",
        ),
    ]
