# Generated by Django 6.0 on 2026-01-25 00:18

import uuid
from django.db import migrations


def populate_uid(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    for org in Organization.objects.all():
        if not org.uid:
            org.uid = uuid.uuid4()
            org.save(update_fields=["uid"])


def reverse_populate_uid(apps, schema_editor):
    # No reverse operation needed
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_organization_uid"),
    ]

    operations = [
        migrations.RunPython(populate_uid, reverse_populate_uid),
    ]
