# Generated by Django 6.0 on 2026-01-25 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_populate_organization_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
