# Generated by Django 6.0 on 2026-01-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organization_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
